Kodutöö3
Papilegend/Ryhm-E pull request #47
Opened 2023-05-26 10:08 UTC by Papilegend

Keegi saaks vaadata selle üle ja praeguse errori ära fixida?

2023-05-26 10:36 UTC, elsaneth commented on kt3.py
> +    values = (username,)
kas siin peabki olema koma?

2023-05-26 11:28 UTC, elsaneth requested changes
SQL create table scripti pole niimoodi vaja. See tabel tuleb andmebaasis teha, kas pythoni programmis või mingil muul moel.

2023-05-26 16:15 UTC, Papilegend commented on kt3.py
> +    values = (username,)
Ja

2023-05-26 16:15 UTC, Papilegend commented
> SQL create table scripti pole niimoodi vaja. See tabel tuleb andmebaasis teha, kas pythoni programmis või mingil muul moel.

Nõus

2023-05-27 07:01 UTC, elsaneth approved these changes
Väga hea töö! 🤓💪

2023-05-27 09:02 UTC, merged